version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: user_mgmt_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: user_management
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - user_management_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user_mgmt_service
    environment:
      - DB_HOST=mariadb
      - DB_USER=user
      - DB_PASSWORD=userpassword
      - DB_NAME=user_management
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    networks:
      - user_management_network

networks:
  user_management_network:
    driver: bridge

volumes:
  mariadb_data:
